[package]
name = "coolercast"
description = "Drives DeepCool cooler displays without the official app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
coolercast-core.workspace = true

[build-dependencies]
embed-resource.workspace = true

[target.'cfg(windows)'.dependencies]
windows-service.workspace = true

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_Power",
    "Win32_UI_WindowsAndMessaging",
]

[lints]
workspace = true
