# Link the C runtime statically on Windows so the executables do not need the Visual C++
# Redistributable (VCRUNTIME140.dll) on the target PC.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
